### ISSUE TITLE
Draggable column is buggy, especially on Trackpads

### ISSUE THREAD

**Issue by awesomephant** [roccopung/export-radio#1]
This effect seem to be very buggy, especially on trackpad. The js file is resize.js

**Comment by awesomephant** [comment]
Okay, I think there are a few factors making this interaction feel clunky:

- The current implementation doesn't register _where_ on the drag handle the user put their mouse down, so the left edge of the handle snaps to the current mouse position. As a result the calculation for the column sizes is incorrect. The solution is to look at the `boundingBox` of the handle and calculating the relative mouse position.
- When you move your mouse over an iframe it captures the `mousemove` event, causing the dragging interaction to stop unexpectedly. We solve that by setting all iframes on the page to `pointer-events: none` while we're moving the handle.
- In the current implementation you inadvertantly select images and text on the page as you move the handles. This is solved by calling `preventDefault()` on the mouse events.

I have a commit coming up here shortly that does this, and indeed the dragging interaction feels much more stable. I also rewrote it without to reduce dependencies.

**Comment by roccopung** [comment]
Thank you Max

Also for the detailed explanation, very, very useful for me to understand.

Tomorrow I will look at everything!

**Comment by roccopung** [comment]
Hi, I've noticed that now the columns are much easier to drag, but there is some problem with the right column when you, resize the screen. Do you have that that as well?

**Comment by awesomephant** [comment]
I take it your're referring to this?

![screenshot](https://user-images.githubusercontent.com/2758247/103447259-840e8100-4c80-11eb-8e77-3fbd2a66db92.png)

I'll move that into a new issue, #3
