### ISSUE TITLE
Embed Instagram latest post

### ISSUE THREAD

**Issue by roccopung** [roccopung/export-radio#4]
Hi Max, 

I have two other questions for you, on which you may have some experience. If that's not the case or they take too much time, feel free to tell me. The first one is: do you know how to embed the Instagram latest post in the contact section? 

I see it can be done with APIs but never worked with them

**Comment by awesomephant** [comment]
That used to be easy, but Instagram tightened up their API a lot a few years ago. It would be a pretty big effort now, maybe there's a simpler solution like a link to the profile?

**Comment by roccopung** [comment]
Yes, looking a bit into it, I had a similar feeling as well. Agreed.
