### ISSUE TITLE
Embedding a Playlist

### ISSUE THREAD

**Issue by roccopung** [roccopung/export-radio#5]
The other question is on the broadcastings section: do you know how to embed a playlist with the possibility to skip tracks, from Mixcloud? 

Because I've looked at it, and embed the player but doesn't give me the possibility to see the tracklist or skip. what they are looking for, is basically a dynamic way to listen to their previous broadcastings.

**Comment by awesomephant** [comment]
Hm, if Mixcloud doesn't support it the most stable way to do it might be to keep information about the individual shows in your CMS and rendering a playlist interface yourself - in fact I see you've done the interface part already. That's what we did for [Strike Radio](http://strikeradio.org/shows/). The only downside is that you have to add new shows to the CMS manually.

**Comment by roccopung** [comment]
Exactly! That is the problem I was trying to solve... Because in the case of Export Radio, they are having many shows and the project is meant to go on for quite a lot of time, so adding manually each show could be a bit too much effort. Especially because this player only enables audio files and they would be huge (more than 1 hour each).

However, if we do as you suggest with Mixcloud, we could perhaps embed the single show, and then use the buttons "next" and "prev" to load other embedded iframes. That would require changing the shows manually in the CMS but maybe it's not that annoying? How do you feel about that in terms of usability

**Comment by awesomephant** [comment]
I looked at the Mixcloud API a little bit, and maybe we can do a little of both solutions. We can pull in the shows dynamically (so you don't have to manage them in the CMS manually), and use the Mixcloud iframe to play the actual audio, as you suggest. I've written a [prototype of this here](https://codepen.io/maxakohler/full/poELmKj). Codepen doesn't like the embedded iframe, but it's supposed to look like this:

![image](https://user-images.githubusercontent.com/2758247/103538745-b392d880-4e8e-11eb-99f2-c7a6ce80b694.png)

The image comes from the API, so you wouldn't have to add that by hand either. I think usability-wise it's pretty decent. There's a couple things we can't do, like auto-playing the next track when the current one is finished, but maybe that's acceptable?

**Comment by roccopung** [comment]
Wow, given our constraints, this looks just perfect to me. Great solution Max. Do you want to push it on our main? I can adapt with Export Radio css

**Comment by awesomephant** [comment]
Just to double-check, do you want me to replace the existing player with this?

**Comment by roccopung** [comment]
Yes please, it would be great!
