### ISSUE TITLE
Main folder weight

### ISSUE THREAD

**Issue by roccopung** [roccopung/export-radio#6]
Hi Max, I've looked at all your changes and they seem to work just perfectly. I'm honestly impressed, thank you so much!

I have a question for you: today I downloaded your main folder, which was around 12MB. I `git pull` with mine (that has some more projects uploaded) and merged them. Everything works fine, except that my folder now weighs 45MB, and if I look inside it I can see that the sum of the folders should weigh in total around 20 MB. So there is a 20 excess that I don't know where it comes from. Do you have any idea why this may happen?

**Comment by awesomephant** [comment]
I'm not sure, but maybe it's the ```.git``` folder? I think that's hidden depending on your operating system settings, and could be about that heavy. It contains all previous versions of your project files in a compressed form and makes things like Github work. ```git pull``` would probably create that folder. But it could be something else entirely, too.

**Comment by roccopung** [comment]
Yes I think you're right, it's very likely to be the problem. 

.Git is the only folder remaining and there are lots of versions stored there. Thanks!
