### ISSUE TITLE
Tags page

### ISSUE THREAD

**Issue by roccopung** [roccopung/export-radio#7]
Max, I open the last request from the Export team, which I forward to you because I'm struggling with the logic of it and I'm not sure I'll be able to make it in time. 

Basically, they want a tag page like the one of [http://content-free.net/tags](http://content-free.net/tags) based on the "Category" of the projects. I guess this is a Kirby thing, so in case it's something that you have to study from scratch and would take you a lot of time please tell me.

This link is the one that I referred, but somehow struggled to apply:
[https://getkirby.com/docs/cookbook/content/filtering-with-tags](https://getkirby.com/docs/cookbook/content/filtering-with-tags)

**Comment by awesomephant** [comment]
It looks doable, but if we do a whole separate tags page I have a few more questions:

- What happens when you click on a tag? Do you go back to the homepage, but now you only see projects of that tag, or is there a different "search results" page like on Content Free?
- How do you get to this tags page in the first place, and how do you get back to the homepage?

I think a lighter solution might be to do the filtering inside the homepage, kind of like [on this page](https://adalbertolonardi.com/projects/). I've already written the code for that, so it would be easy to apply here. What do you think?

**Comment by roccopung** [comment]
I think that for the case of Export-Radio, it would be difficult to have a fixed list of tags to filter because the students' projects will be numerous and very different and they will probably categorize them in unexpected ways. So for me, a good solution could be:

1. You have a "tags" button in the homepage, central column
2. When you click on that, you're linked to a "tags" page with all tags present in the website in form of list
3. Clicking on a tag there, you are linked to a page with all the relative projects, and then from them, you select the one that you want to see.

And the page "tags" could look like the ones in the mobile version: with a header that can redirect you to the homepage.

However, I know that Louise is also waiting for a reply from Laura to see if the developer of Content-Free can help with it, since he coded it already on Kirby. So for the moment, I ask you if you can please put it on pause and let's see what they reply :)

**Comment by awesomephant** [comment]
I can do that, too, but happy to wait. I know the other guy (his name is Max, too!), he might well be up for it.

**Comment by roccopung** [comment]
Awesome! I'll keep you updated on that :)

**Comment by roccopung** [comment]
I come back on this since the other Max hasn't replied yet. Regarding the "tags", they would like them to be exactly like Content-Free, the one that we discussed the other day:

> 1. You have a "tags" button in the homepage, central column
> 2. When you click on that, you're linked to a "tags" page with all tags present in the website in form of list
> 3. Clicking on a tag there, you are linked to a page with all the relative projects, and then from them, you select the one that you want to see.
> 
> And the page "tags" could look like the ones in the mobile version: with a header that can redirect you to the homepage.

And their concern is that they should be able to create/update tags for each project, without going to the code so possibly from the Kirby panel. My issue with this is that I know how to create tags in Kirby but I can't figure out how the logic works to connect and display them...

In the meanwhile, in the new branch, I created a "Tags" page + "Tags" button

**Comment by awesomephant** [comment]
Aight I'll take a look.

**Comment by awesomephant** [comment]
I've built out the logic, I'll leave the styling to you. I don't know if you wanted to copy the image thing from Content-Free, but I wrote it anyway:

![image](https://user-images.githubusercontent.com/2758247/104060545-f76b4200-51ee-11eb-94dc-7abf9e00af21.png)

This pulls in the first image from the first project in each tag, The tags page should auto-populate itself as you add new tags to individual projects. Just keep in mind that different spellings of the same tag (like ```audio``` and ```Audio```) will be recognised as two different tags.

**Comment by roccopung** [comment]
A thousand thank you. It was just perfect, the only edit that I made was a string for multi-words tags that apparently Kirby sees as exceptions. Tonight I have fixed the last bits and bobs, pushed them in the new branch, and sent the website to Export team to check. I didn't find any problems by the way. Fingers crossed we made it!!
