### ISSUE TITLE
Shall we prevent the website to load all the projects simultaneously? 

### ISSUE THREAD

**Issue by roccopung** [roccopung/export-radio#8]
Thinking about the performances of the website, I imagine that we will have a long list of projects in the central column the more time passes. Do you know how we could make it load smart, like only the latest projects load and then projects load only accordingly to scroll?

**Comment by awesomephant** [comment]
You could throw a ```loading=lazy``` attribute on the images so they only load when you scroll to them. But unless there's going to be thousands of items I wouldn't be too worried beyond that.

**Comment by roccopung** [comment]
Will do the `loading=lazy`, just in case. Thank you as always
